[package]
name = "clickhouse-sink"
version = "0.1.0"
edition.workspace = true

[dependencies]
clickhouse = "0.15.1"
kernel-model = { version = "0.1.0", path = "../kernel-model" }
otlp-receiver = { version = "0.1.0", path = "../otlp-receiver" }
pricing = { version = "0.1.0", path = "../pricing" }
serde = { version = "1.0.229", features = ["derive"] }

[dev-dependencies]
tokio = { version = "1.53.1", features = ["macros", "rt-multi-thread"] }
