[package]
name = "otlp-receiver"
version = "0.1.0"
edition.workspace = true

[dependencies]
kernel-model = { version = "0.1.0", path = "../kernel-model" }
prost = "0.14.4"
tonic = { version = "0.14.6", features = ["tls-ring", "tls-webpki-roots"] }
tonic-prost = "0.14.6"

[build-dependencies]
protoc-bin-vendored = "3.2.0"
tonic-prost-build = "0.14.6"

[dev-dependencies]
tokio = { version = "1.53.1", features = ["macros", "rt"] }
